### ISSUE TITLE
Firebase Auth fails on GAE Standard due to missing email claim

### ISSUE THREAD

**Issue by fredriks** [cloudendpoints/endpoints-management-java#25]
Using a Firebase Auth token on App Engine Standard with Cloud Endpoints results in a 503 with the following response body:
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "backend error"
   }
  ],
  "code": 503,
  "message": "backend error"
 }
````

This is the trace taken from GAE logs for the 503 backendError request:
```
com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler handle: exception occurred while invoking backend method (EndpointsMethodHandler.java:124)
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.api.auth.UserInfo.<init>(UserInfo.java:46)
	at com.google.api.auth.Authenticator.toUserInfo(Authenticator.java:278)
	at com.google.api.auth.Authenticator.authenticate(Authenticator.java:109)
	at com.google.api.server.spi.auth.EspAuthenticator.authenticate(EspAuthenticator.java:83)
	at com.google.api.server.spi.request.Auth.authenticate(Auth.java:101)
	at com.google.api.server.spi.request.ServletRequestParamReader.getUser(ServletRequestParamReader.java:192)
	at com.google.api.server.spi.request.ServletRequestParamReader.deserializeParams(ServletRequestParamReader.java:137)
	at com.google.api.server.spi.request.RestServletRequestParamReader.read(RestServletRequestParamReader.java:124)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:349)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:114)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:102)
	at com.google.api.server.spi.dispatcher.PathDispatcher.dispatch(PathDispatcher.java:49)
	at com.google.api.server.spi.EndpointsServlet.service(EndpointsServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.api.control.ControlFilter.doFilter(ControlFilter.java:296)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.api.control.ConfigFilter.doFilter(ConfigFilter.java:120)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)
```

The issue seem to be that com.google.api.auth.[Authenticator](https://github.com/cloudendpoints/endpoints-management-java/blob/v1.0.2/endpoints-auth/src/main/java/com/google/api/auth/Authenticator.java#L266) and com.google.api.auth.[UserInfo](https://github.com/cloudendpoints/endpoints-management-java/blob/v1.0.2/endpoints-auth/src/main/java/com/google/api/auth/UserInfo.java#L46) assume that there is an email claim in the Firebase Auth token which is not always the case.

Using [jwt.io](https://jwt.io) this is the contents of my token:
```json
{
  "iss": "https://securetoken.google.com/<AUDIENCE>",
  "name": "<FIREBASE USER NAME>",
  "picture": "https://scontent.xx.fbcdn.net/....",
  "aud": "<AUDIENCE>",
  "auth_time": 1489965537,
  "user_id": "<FIREBASE USER ID>",
  "sub": "<FIREBASE USER ID>",
  "iat": 1489965538,
  "exp": 1489969138,
  "firebase": {
    "identities": {
      "facebook.com": [
        "<FACEBOOK USER ID>"
      ]
    },
    "sign_in_provider": "facebook.com"
  }
}
```

The token I tested with was created using firebase javascript SDK:
```javascript
user.getToken(true).then(console.log)
```

**Comment by dayj** [comment]
I am seeing this same issue using Firebase Phone Number Auth with EspAuthenticator. 

Is there a workaround or at least an update on when this will be addressed?

**Comment by fredriks** [comment]
I ended up working around the problem by overwriting the Authenticator.toUserInfo, to handle the missing email claim instead of throwing.

**Comment by digaresc** [comment]
Hi! I'm having exactly the same problems that you have. Can you help giving an example of you overwrited the method? Or the solution?

Thanks in advance.

**Comment by g-ericso** [comment]
Yes, we are having the same problem when client access token is generated using anonymous account. Can someone remove the "checkNotNull(email)" in UserInfo.java.

**Comment by g-ericso** [comment]
#34 Since this PR is merged, @fredriks, you can test the version 1.0.6 tomorrow to see if it fixes your issue.

**Comment by fredriks** [comment]
Cool, thanks @g-ericso!

**Comment by g-ericso** [comment]
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22endpoints-management-control-appengine-all%22

The version 1.0.6 is ready. Good luck!
