### ISSUE TITLE
New fields in service configurations can cause failures in the ServiceManagementConfigFilter

### ISSUE THREAD

**Issue by KyleWiese** [cloudendpoints/endpoints-management-java#69]
When a new field is added to the service config object, if the corresponding proto library in the endpoints java package is not updated, the parser in ServiceManagementConfigFilter will fail to convert the service config object into its java representation with the following error

```
Failed to parse the HTTP response as service configuration
com.google.api.config.ServiceConfigException: Failed to parse the HTTP response as service configuration
```

Adding `.ignoringUnknownFields()` to the parser should fix this issue.

**Comment by msilva-basis** [comment]
I am also running into this issue during the startup of an App Engine app.

After deploying endpoints configuration using the `gcloud endpoints services deploy` command, there seems be a new `metadata` field added to the config and App Engine is no longer working.

```
Failed to load service
endpoints.repackaged.com.google.api.config.ServiceConfigException: Failed to parse the HTTP response as service configuration
```

```
Caused by: endpoints.repackaged.google.protobuf.InvalidProtocolBufferException: Cannot find field: metadata in message google.api.MetricDescriptor
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1417)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1377)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:1907)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.mergeRepeatedField(JsonFormat.java:1642)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1575)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1419)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1377)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1259)
	at endpoints.repackaged.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:407)
	at endpoints.repackaged.com.google.api.config.ServiceConfigSupplier.parseHttpResponse(ServiceConfigSupplier.java:194)
	... 34 more
```

**Comment by KyleWiese** [comment]
This issue should be fixed in version `1.0.15`. Please try updating your dependency and let me know if things still aren't working.

**Comment by msilva-basis** [comment]
Thank you, I updated the dependency to 1.0.15 and it is working now.

**Comment by TheCloudGate** [comment]
I have the same problem, but when I try to update my maven dependencies por endpoints-management to 1.0.15 I get the following error: 

`[WARNING] The POM for com.google.endpoints:endpoints-management-protos:jar:1.0.15 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`

The dependencies I have updated to 1.0.15 are **endpoints-management-control-appengine** and **endpoints-framework-auth**.

**Comment by KyleWiese** [comment]
Hi,

You need to also update your `endpoints-framework-auth` dependency to 1.0.15. Additionally if you're updating from v1.0.11 or older _and_ cannot use the `endpoints-management-control-appengine-all` dependency, you may need to import the following dependencies as well:

* `com.google.apis:google-api-services-servicemanagement` version `v1-rev14-1.22.0`
* `com.google.protobuf:protobuf-java-util` version `3.9.1`
